import {Dimensions, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  mainContainer: {
    width: width,
    height: height,
    marginBottom: -110,
  },
  topBarContainer: {
    width: width,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5BF45',
    height: 82,
    position: 'relative',
    top: 0,
    // marginVertical: 50,
    // marginBottom: -150,
    // paddingBottom: -500,
  },
  headingText: {
    fontWeight: '600',
    fontSize: 24,
    color: '#18161B',
    alignSelf: 'center',
    alignItems: 'center',
  },
  cartContainer: {
    marginLeft: 16,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'flex-end',
    // borderWidth: 1,
    padding: 10,
    width: '90%',
    backgroundColor: '#FFFFFF',
    paddingBottom: 25,
    borderRadius: 10,
    // marginBottom: 250,
    // height: height,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#18161B',
    width: 150,
    height: 40,
    marginTop: 12,
  },
  productImage: {
    height: 87,
    width: 98,
    borderRadius: 5,
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 120,
    marginTop: -15,
  },
  priceText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#F62B2A',
  },
  offText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#BAB9BB',
    textDecorationLine: 'line-through',
  },
  counterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    // borderWidth: 1,
    width: 125,
    height: 32,
    backgroundColor: '#F5BF45',
    borderRadius: 60,
    padding: 10,
    marginTop: 12,
  },
  decrementText: {
    fontWeight: '500',
    fontSize: 12,
    marginTop: 0,
  },
  counterText: {
    fontWeight: '600',
    fontSize: 16,
    color: '#000000',
    width: 50,
    textAlign: 'center',
    height: 35,
    paddingTop: 5,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#FFFFFF',
  },
  totalPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
  },
  bottomPriceContainer: {
    padding: 35,
    position: 'absolute',
    bottom: 0,
    width: width,
    // top: 0,
    backgroundColor: 'white',
    // borderWidth: 1,
  },
  titlePriceText: {
    color: '#99959E',
    fontWeight: '500',
    fontSize: 16,
  },
  priceTextofcart: {
    color: '#18161B',
    fontWeight: '500',
    fontSize: 18,
  },
  priceText2: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F62B2A',
  },
  bottomline: {
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    opacity: 0.3,
  },
});
