import {Dimensions, StyleSheet} from 'react-native';

const {width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  cartContainer: {
    marginLeft: 16,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
    width: '92%',
    height: 136,
    backgroundColor: '#FFFFFF',
    paddingBottom: 25,
    borderRadius: 10,
  },
  nameText: {
    color: '#18161B',
    fontSize: 16,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  deliveryAddresstext: {
    color: '#BAB9BB',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'capitalize',
    // borderWidth: 1,
    width: 250,
    height: 66,
    marginTop: 10,
    lineHeight: 22,
  },
  addressTextContainer: {
    flexDirection: 'column',
    marginHorizontal: 8,
    paddingLeft: 10,
  },
  outerCircle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    opacity: 0.7,
    borderWidth: 2,
    borderColor: '#BAB9BB',
    padding: 3,
  },
  innerCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  topBarContainer: {
    width: width,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5BF45',
    height: 70,
    // position: 'relative',
    top: 0,
    // marginVertical: 50,
    // marginBottom: -150,
    // paddingBottom: -500,
  },
  headingText: {
    fontWeight: '600',
    fontSize: 24,
    color: '#18161B',
    alignSelf: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    height: 85,
    width: 135,
    // borderWidth: 1,
    // marginRight: 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    position: 'absolute',
    right: 25,
    top: 48,
  },
  editText: {
    color: '#18161B',
    fontWeight: '600',
    fontSize: 14,
    width: 50,
    padding: 5,
    marginHorizontal: 18,
    paddingTop: 9,
  },
  bottomDash: {
    borderBottomWidth: 1,
    borderBottomColor: '#B8B7B9',
    opacity: 0.5,
    position: 'relative',
    top: -10,
  },
  deleteText: {
    color: '#18161B',
    fontWeight: '600',
    fontSize: 14,
    marginHorizontal: 20,
  },
  shadowProp: {
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    elevation: 3,
    backgroundColor: 'white',
  },
});
