import {Dimensions, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  mainContainer: {
    marginBottom: 100,
  },
  topBarContainer: {
    width: width,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // marginHorizontal: 10,
    backgroundColor: '#F5BF45',
    height: 82,
  },
  menuIcon: {
    width: 48,
    height: 48,
    borderRadius: 48 / 2,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  menuIcon2: {
    backgroundColor: '#E7AC27',
    width: 48,
    height: 48,
    borderRadius: 48 / 2,
    padding: 10,
    alignSelf: 'center',
    marginLeft: 12,
    marginTop: 15,
  },
  logoImage: {
    width: 120,
    height: 45,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  inputField: {
    width: width / 1.6,
    height: 54,
    paddingLeft: 20,
    borderColor: '#A4A1A1',
  },
  pincodeText: {
    fontSize: 15,
    fontWeight: '600',
    paddingLeft: 3,
    color: '#A4A1A1',
  },
  headingText: {
    fontWeight: '600',
    fontSize: 24,
    // textAlign: 'center',
    color: '#18161B',
    alignSelf: 'center',
    alignItems: 'center',
    // justifyContent: 'center',
  },
  image: {
    width: 126,
    height: 126,
    borderRadius: 126 / 2,
  },
  itemView: {
    height: 180,
    flex: 1,
    alignItems: 'center',
    paddingTop: 15,
    backgroundColor: 'white',
    // shadowColor: 'black',
    // shadowOffset: {width: 1, height: 1},
    // shadowOpacity: 0.2,
    // elevation: 1,
  },
  title1: {
    color: 'black',
    fontWeight: 'bold',
    padding: 5,
  },
  flatlistContainer: {
    paddingTop: 25,
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  bestText: {
    fontWeight: '600',
    fontSize: 20,
    fontStyle: 'normal',
    color: '#18161B',
    paddingHorizontal: 15,
    lineHeight: 40,
    // paddingTop: 15,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#18161B',
    width: 150,
    height: 40,
    marginTop: 12,
  },
  productImage: {
    height: 95,
    width: '100%',
    borderRadius: 5,
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 120,
    marginTop: -15,
  },
  priceText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#F62B2A',
  },
  offText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#BAB9BB',
    textDecorationLine: 'line-through',
  },
  counterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    // borderWidth: 1,
    width: '100%',
    height: 38,
    backgroundColor: '#F5BF45',
    borderRadius: 60,
    padding: 10,
    marginTop: 20,
  },
  decrementText: {
    fontWeight: '500',
    fontSize: 15,
  },
  counterText: {
    fontWeight: '600',
    fontSize: 16,
    color: '#000000',
    width: 50,
    textAlign: 'center',
    height: 35,
    paddingTop: 5,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#FFFFFF',
  },
  flatContainer: {
    marginLeft: 16,
    marginVertical: 8,
  },

  itemName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#18161B',
    // fontFamily: 'Montserrat Alternates',
    width: 150,
    height: 40,
    marginTop: 12,
  },
  categoryFlatlist: {
    marginVertical: 8,
    width: 150,
    height: 236,
    marginHorizontal: 15,
  },
});
