import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  headerContainer: {
    flexDirection: 'row',
    backgroundColor: '#F5BF45',
    height: 203,
    paddingTop: 25,
  },
  outerContainer: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    //  backgroundColor: 'white'
  },
  profileText: {
    color: '#18161B',
    fontSize: 24,
    fontWeight: '600',
    textTransform: 'capitalize',
    textAlign: 'center',
    paddingHorizontal: 120,
  },
  roundMusicApp: {
    width: 46,
    height: 46,
    borderRadius: 60,
    position: 'absolute',
    backgroundColor: '#F72B2A',
    right: 0,
    top: 15,
  },
  headsetIcon: {
    textAlign: 'center',
    padding: 12,
  },
  innerContainer: {
    width: 190,
    height: 190,
    borderRadius: 190 / 2,
    padding: 10,
    backgroundColor: 'white',
  },
  profilePic: {
    width: 170,
    height: 170,
    borderRadius: 170 / 2,
    resizeMode: 'contain',
  },
  textInput: {
    borderWidth: 2,
    width: 320,
    height: 60,
    borderRadius: 60,
    alignSelf: 'center',
    backgroundColor: 'white',
    paddingLeft: 30,
    // zIndex: 0,
    position: 'absolute',
  },
  textInputLabel: {
    position: 'absolute',
    left: 65,
    color: '#18161B',
    fontWeight: '600',
    fontSize: 14,
    zIndex: 1,
    backgroundColor: 'white',
    paddingLeft: 5,
    borderRadius: 5,
  },
  centeredView: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    borderWidth: 1,
    // opacity:0.6
    // backgroundColor: 'black',
  },
  modalView: {
    // margin: 20,
    backgroundColor: 'white',
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
    height: 150,
    opacity: 1,
    // borderWidth: 1,
    position: 'absolute',
    bottom: 0,
    borderWidth: 1,
    marginBottom: 0,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    color: '#18161B',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
  },
  modalDescriptionText: {
    color: '#A9A9A9',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 26,
    textTransform: 'capitalize',
    width: 318,
    height: 74,
    textAlign: 'center',
  },
  pinscreenInput: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 60,
    paddingTop: 20,
    fontSize: 16,
    fontWeight: '500',
    textAlignVertical: 'top',
    color: 'black',
    // borderWidth: 1,
    borderRadius: 60,
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 10,
  },
  roundMusicApp2: {
    width: 60,
    height: 60,
    borderRadius: 60,
    backgroundColor: '#F72B2A',
    // marginHorizontal: 10,
    marginLeft: -20,
    marginRight: 40,
  },
  headsetIcon2: {
    textAlign: 'center',
    padding: 15,
  },
});
