import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  topBarContainer: {
    width: width,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5BF45',
    height: 70,
    position: 'relative',
    top: 0,
  },
  headingText: {
    fontWeight: '600',
    fontSize: 24,
    color: '#18161B',
    alignSelf: 'center',
    alignItems: 'center',
  },
  cartContainer: {
    marginLeft: 20,
    marginTop: 20,
    padding: 20,
    width: '90%',
    backgroundColor: '#FFFFFF',
    paddingBottom: 25,
    borderRadius: 10,
    paddingLeft: 25,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#18161B',
    width: 150,
    height: 40,
    marginTop: 12,
  },
  productImage: {
    height: 87,
    width: 98,
    borderRadius: 5,
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 120,
    marginTop: -15,
  },
  priceText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#F62B2A',
  },
  offText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#BAB9BB',
    textDecorationLine: 'line-through',
  },
  counterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    // borderWidth: 1,
    width: 125,
    height: 32,
    backgroundColor: '#F5BF45',
    borderRadius: 60,
    padding: 10,
    marginTop: 12,
  },
  maincontainer: {
    backgroundColor: '#E5E5E5',
    paddingBottom: 40,
  },
  daytext: {
    color: '#18161B',
    fontSize: 15,
    fontWeight: '600',
    textTransform: 'capitalize',
    textAlign: 'center',
    marginTop: 20,
  },
  ordertextid: {
    color: '#18161B',
    fontWeight: '600',
    fontSize: 16,
  },
  cardbottomcontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',

    marginTop: 8,
  },
  pricetext2: {
    color: '#F62B2A',
    fontSize: 15,
    fontWeight: '600',
    textTransform: 'capitalize',
    marginTop: 8,
  },
  timecontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  timetext: {
    color: '#A2A3A5',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'capitalize',
    marginLeft: 5,
  },
  imagecontainer: {
    width: 60,
    height: 60,
    borderRadius: 60 / 2,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
  },
  rightimage: {
    width: 48,
    height: 46,
    borderRadius: 48 / 2,
    resizeMode: 'contain',
    marginTop: 14,
    position: 'absolute',
    top: -8,
    padding: 20,
    left: 5,
    zIndex: -1,
  },
});
