import {Dimensions, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('window');

export const Styles = StyleSheet.create({
  image: {height: '68%', width: width, marginTop: -20, borderWidth: 1},
  container: {
    width: 320,
    height: 416,
    borderRadius: 20,
    position: 'absolute',
    top: 260,
    backgroundColor: 'white',
    alignItems: 'center',
    padding: 15,
    alignSelf: 'center',
  },
  titleText: {fontWeight: '600', color: 'black', fontSize: 18, marginTop: 30},
  container2: {flexDirection: 'row', padding: 10},
  offerPrice: {color: '#F62B2A', fontSize: 15, fontWeight: '600'},
  actualPrice: {
    fontSize: 15,
    paddingLeft: 15,
    textDecorationLine: 'line-through',
    color: '#A9A9A9',
  },
  discriptionText: {
    textAlign: 'center',
    marginTop: 10,
    color: '#A9A9A9',
    width: 276,
    lineHeight: 24,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  container3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    borderBottomWidth: 0.3,
    borderColor: '#C4C4C4',
    // borderWidth: 1,
    width: 240,
  },
  peices: {
    color: '#18161B',
    paddingRight: 20,
    fontSize: 16,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  peicesQty: {
    color: '#18161B',
    paddingLeft: 60,
    fontSize: 16,
    fontWeight: '500',
  },
  container4: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderWidth: 1,
    width: 240,
    padding: 10,
  },
  packs: {
    color: '#18161B',
    paddingRight: 20,
    fontSize: 16,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  packsQty: {
    color: '#18161B',
    paddingLeft: 60,
    fontSize: 16,
    fontWeight: '500',
  },
  container5: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 266,
    margin: 5,
    borderRadius: 60,
    backgroundColor: '#F5BF45',
    height: 60,
    textTransform: 'capitalize',
  },
  decrement: {
    borderRightWidth: 0.9,
    borderColor: 'white',
    paddingHorizontal: 25,
  },
  quantity: {
    textTransform: 'capitalize',
    fontSize: 22,
    fontWeight: '500',
    color: '#000000',
    paddingVertical: 15,
  },
  increment: {
    borderLeftWidth: 0.3,
    borderColor: 'white',
    paddingHorizontal: 25,
  },
  incrementText: {
    color: 'white',
    fontSize: 24,
    paddingBottom: 5,
    paddingTop: 15,
  },
});
